# Conda

Now, let's get to environment. First, let's use conda to create an environment.

    conda create --name csci347 python=3.8

And activate the environment

    conda activate csci347

## Packages

Install packages

    conda install pip numpy jupyter pandas scikit-learn matplotlib openpyxl

Packages used in this class:

- `pip`
- `numpy`
- `jupyter`
- `pandas`
- `scikit-learn`
- `matplotlib`
- `openpyxl`

> Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex
    <br><br>For example:

    $ conda install scikit-learn-intelex
    $ python -m sklearnex my_application.py

## Enviroment

List conda environments

    conda env list

### environment.yml

These environments can become very complex in complex projects, so it is often a good idea to capture your environment and keep it in version control. Most often people keep it in a file called `environment.yml`.

### Create YML

We can export the environment with the following command:

    conda env export --file environment.yml

This produces a file called environment.yml take a look at it.

### Import YML Environment

    conda env create -f environment.yml
    
### Config Stuff

disable the automatic base activation:

    conda config --set auto_activate_base false

